# Generated by Django 3.2 on 2022-02-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220131_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
