# Generated by Django 3.2 on 2022-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_ordermodel_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
