# Generated by Django 3.2 on 2022-06-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20220616_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('town', models.CharField(blank=True, max_length=50)),
                ('county', models.CharField(blank=True, max_length=15)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_shipped', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='restaurant.MenuItem')),
            ],
        ),
    ]
